[package]
name = "pizzaboxer/bloxstrap-rpc-sdk"
description = "Take advantage of Bloxstrap's features from inside your game with BloxstrapRPC. More information is available at https://github.com/pizzaboxer/bloxstrap/wiki/Integrating-Bloxstrap-functionality-into-your-game."
authors = ["pizzaboxer", "ElusiveEpix"]
version = "1.0.1"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = ["src**", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
